version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "lchtangen"
    assignees:
      - "lchtangen"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group minor and patch updates
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: increase

  # npm dependencies (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "lchtangen"
    assignees:
      - "lchtangen"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    ignore:
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: increase

  # Frontend web-app dependencies
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "lchtangen"
    assignees:
      - "lchtangen"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    ignore:
      # Pin specific versions that are known stable
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      ui-libraries:
        patterns:
          - "@radix-ui/*"
          - "class-variance-authority"
          - "clsx"
          - "tailwind*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "typescript"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: increase

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "lchtangen"
    assignees:
      - "lchtangen"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/deployment/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "lchtangen"
    assignees:
      - "lchtangen"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    ignore:
      # Be careful with base image updates
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # VSCode Extension dependencies
  - package-ecosystem: "npm"
    directory: "/vscode-extension"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "lchtangen"
    assignees:
      - "lchtangen"
    labels:
      - "dependencies"
      - "vscode-extension"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      vscode-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

# Dependabot Configuration Notes:
# 
# - Weekly updates on Mondays at 9 AM UTC
# - Major version updates are ignored by default for stability
# - Minor and patch updates are grouped to reduce PR noise
# - All PRs are automatically assigned and labeled
# - Maximum 10 PRs for Python, 5 for npm (root), 10 for frontend
# - Versioning strategy: increase (always update to latest compatible)
#
# To enable Dependabot:
# 1. This file must be in the .github directory
# 2. GitHub Dependabot must be enabled in repository settings
# 3. Security alerts should be enabled for automatic security updates
#
# Security Updates:
# - Dependabot automatically creates PRs for security vulnerabilities
# - These PRs are prioritized and should be reviewed immediately
# - Security updates bypass the weekly schedule
#
# Manual Triggers:
# - You can manually trigger Dependabot updates from the GitHub UI
# - Go to Insights > Dependency graph > Dependabot
# - Click "Check for updates" for any ecosystem