apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: samplemind
  labels:
    app: celery-worker
    tier: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
        tier: worker
    spec:
      containers:
      - name: celery-worker
        image: samplemind/backend:latest
        imagePullPolicy: Always
        command: ["celery"]
        args:
          - "-A"
          - "src.samplemind.core.tasks.celery_app"
          - "worker"
          - "-l"
          - "info"
          - "-c"
          - "4"
          - "-Q"
          - "default,audio_processing,ai_analysis,embeddings"
        envFrom:
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: backend-pvc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-worker-hpa
  namespace: samplemind
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-worker
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
