global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert.rules'

# Scrape configuration
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # SampleMind API
  - job_name: 'samplemind-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['samplemind-api:8000']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

# Remote write configuration (optional, for long-term storage)
remote_write:
  - url: 'http://remote-storage:8086/write'
    queue_config:
      max_samples_per_send: 1000
      capacity: 5000
      max_shards: 1000
      max_samples_per_send: 1000
