#!/usr/bin/env bash
# setup-usb.sh — One-command bootstrap for SampleMind AI on Ubuntu 25.10 USB boot
# Usage: bash scripts/setup-usb.sh [--full]
#   --full  Also installs heavy ML deps (torch, transformers, demucs) — adds ~5GB
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPFS_BASE=/tmp/samplemind-dev
FULL_INSTALL=false

for arg in "$@"; do
  [[ "$arg" == "--full" ]] && FULL_INSTALL=true
done

echo "============================================="
echo "  SampleMind AI — USB Boot Setup"
echo "  Ubuntu 25.10 · Persistence .dat mode"
echo "============================================="
echo ""

# ── 1. Minimal system packages ────────────────────────────────────────────────
echo "[1/7] Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends \
  python3.11 python3.11-venv python3.11-dev \
  nodejs npm build-essential curl git \
  ffmpeg libsndfile1-dev portaudio19-dev libportaudio2 \
  docker.io docker-compose-plugin \
  zram-tools 2>/dev/null || \
sudo apt-get install -y --no-install-recommends \
  python3.11 python3.11-venv python3.11-dev \
  nodejs npm build-essential curl git \
  ffmpeg libsndfile1-dev portaudio19-dev libportaudio2 \
  docker.io docker-compose

# Install pnpm globally
sudo npm install -g pnpm@10 --silent

# ── 2. zram compressed swap (4GB) — replaces slow USB swap ───────────────────
echo "[2/7] Configuring zram compressed swap..."
if ! swapon --show | grep -q zram; then
  sudo modprobe zram 2>/dev/null || true
  ZRAM_DEV=$(ls /dev/zram* 2>/dev/null | head -1 || echo "")
  if [[ -n "$ZRAM_DEV" ]]; then
    echo lz4 | sudo tee "$ZRAM_DEV/comp_algorithm" >/dev/null 2>&1 || true
    echo 4G   | sudo tee "$ZRAM_DEV/disksize" >/dev/null 2>&1 || true
    sudo mkswap "$ZRAM_DEV" 2>/dev/null || true
    sudo swapon "$ZRAM_DEV" --priority 100 2>/dev/null || true
    echo "  zram swap active: 4GB compressed"
  else
    echo "  zram device not available — skipping"
  fi
else
  echo "  zram already active"
fi

# ── 3. Kernel tweaks for USB I/O ─────────────────────────────────────────────
echo "[3/7] Tuning kernel for USB I/O..."
sudo sysctl -w vm.swappiness=10 >/dev/null
sudo sysctl -w vm.vfs_cache_pressure=50 >/dev/null
sudo sysctl -w vm.dirty_writeback_centisecs=6000 >/dev/null
echo "  vm.swappiness=10, dirty_writeback=60s"

# ── 4. tmpfs — RAM-based caches (no USB writes for build artifacts) ───────────
echo "[4/7] Mounting tmpfs RAM disk for caches..."
if ! mountpoint -q "$TMPFS_BASE" 2>/dev/null; then
  mkdir -p "$TMPFS_BASE"
  sudo mount -t tmpfs -o size=2G,mode=1777 tmpfs "$TMPFS_BASE"
fi
mkdir -p "$TMPFS_BASE"/{pip,poetry,pnpm,pycache,next,dist}
echo "  tmpfs mounted at $TMPFS_BASE (2GB RAM)"

export PIP_CACHE_DIR="$TMPFS_BASE/pip"
export POETRY_CACHE_DIR="$TMPFS_BASE/poetry"
export PYTHONPYCACHEPREFIX="$TMPFS_BASE/pycache"
export PNPM_STORE_DIR="$TMPFS_BASE/pnpm"

# Write env exports to a sourceable file
cat > "$REPO_ROOT/.env.usb-cache" << EOF
# Auto-generated by setup-usb.sh — source this to redirect caches to RAM
export PIP_CACHE_DIR=$TMPFS_BASE/pip
export POETRY_CACHE_DIR=$TMPFS_BASE/poetry
export PYTHONPYCACHEPREFIX=$TMPFS_BASE/pycache
export PNPM_STORE_DIR=$TMPFS_BASE/pnpm
EOF
echo "  Cache env written to .env.usb-cache (source it in your shell)"

# ── 5. Python virtual environment ────────────────────────────────────────────
echo "[5/7] Installing Python dependencies..."
cd "$REPO_ROOT"

if [[ ! -d ".venv" ]]; then
  python3.11 -m venv .venv
fi
source .venv/bin/activate

pip install --upgrade pip --quiet
pip install poetry --quiet

if $FULL_INSTALL; then
  echo "  Full install (including heavy ML deps — ~5GB extra)..."
  poetry install --no-interaction
else
  echo "  Minimal install (skipping torch/transformers/demucs — saves ~5GB)..."
  echo "  Run 'poetry install --with heavy' later if you need ML features."
  poetry install --without heavy --no-interaction
fi

# ── 6. Node.js dependencies ───────────────────────────────────────────────────
echo "[6/7] Installing Node.js dependencies..."
PNPM_STORE_DIR="$TMPFS_BASE/pnpm" pnpm install --frozen-lockfile --silent

# ── 7. Environment config ─────────────────────────────────────────────────────
echo "[7/7] Configuring environment..."
if [[ ! -f ".env" ]]; then
  cp .env.example .env
  echo "  .env created from .env.example — edit with your API keys"
else
  echo "  .env already exists"
fi

echo ""
echo "============================================="
echo "  Setup complete!"
echo "============================================="
echo ""
echo "Next steps:"
echo "  1. Edit .env with your API keys (ANTHROPIC_API_KEY, etc.)"
echo "  2. Source cache env:  source .env.usb-cache"
echo "  3. Start development: make dev-usb"
echo ""
echo "Storage check:"
df -h / | tail -1 | awk '{print "  Persistence .dat: " $3 " used / " $2 " total (" $5 " full)"}'
echo ""
