apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: samplemind
    user: samplemind
    secureJsonData:
      password: "samplemind123"
    jsonData:
      sslmode: "disable"
      postgresVersion: 15
      timescaledb: false
